<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'ois\\plugintemplate\\core' => '/PluginTemplate/Core.php',
                'ois\\plugintemplate\\plugintemplate' => '/PluginTemplate/PluginTemplate.php',
                'ois\\plugintemplate\\settings' => '/PluginTemplate/Settings.php',
                'ois\\vendor\\pimple' => '/Vendor/Pimple.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd