<?php
/*******************************************************************************
 * WARNING: DO NOT EDIT THIS FILE (your changes will be overwritten)           *
 *                                                                             *
 * This file is managed by Composer, and will be overwritten on install/update *
 ******************************************************************************/

/**
 * Plugin Name: MU Composer Autoloader
 * Plugin URI:  https://github.com/OceanInternet/WP-Plugin-Framework
 * Description: Loads in composer generated autoload.php
 * Version:     1.0.0
 * Author:      Andy Weir <andy@ocean-internet.co.uk>
 * License:     (GPL-2.0+ or GPL-3.0+)
 */

if(!defined('DS')) {

    define('DS', DIRECTORY_SEPARATOR);
}

if(!defined('MU_VENDOR_DIR')) {

    define('MU_VENDOR_DIR', WPMU_PLUGIN_DIR . DS . 'vendor');
}

    require MU_VENDOR_DIR . DS . 'autoload.php';

