<?php
/*******************************************************************************
 * WARNING: DO NOT EDIT THIS FILE (your changes will be overwritten)           *
 *                                                                             *
 * This file is managed by Composer, and will be overwritten on install/update *
 ******************************************************************************/

/**
 * Plugin Name: OIS WordPress Plugin Framework
 * Plugin URI:  https://github.com/OceanInternet/WP-Plugin-Framework
 * Description: (yet another) OOP Wordpress Plugin Framework
 * Author:      Andy Weir <andy@ocean-internet.co.uk>
 * Version:     1.0.1
 * Licence:     (GPL-2.0+ or GPL-3.0+)
 */

if(!defined('DS')) {

    define('DS', DIRECTORY_SEPARATOR);
}

if(!defined('OIS_WPPF_DIR')) {

    define('OIS_WPPF_DIR', WPMU_PLUGIN_DIR . DS . 'vendor' . DS . 'ocean-internet' . DS . 'wp-plugin-framework');

    require OIS_WPPF_DIR . DS . 'bootstrap.php';
}
