<?php
/*******************************************************************************
 * WARNING - DO NOT EDIT THIS FILE (your changes will be overwritten)          *
 *                                                                             *
 * This file is managed by Composer, and will be overwritten on install/update *
 ******************************************************************************/
 
/**
 * Plugin Name: OIS WP Plugin Framework
 * Description: Loads in OIS WP Plugin Framework
 * Author:      Andy Weir
 */



if(!defined('DS')) {

    define('DS', DIRECTORY_SEPARATOR);
}

if(!defined('OIS_WPPF_DIR')) {

    define('OIS_WPPF_DIR', WPMU_PLUGIN_DIR . DS . 'vendor' . DS . 'ocean-internet' . DS . 'wp-plugin-framework');
}

require OIS_WPPF_DIR . DS . 'bootstrap.php';
